### ISSUE TITLE
Implementation of hashType still does not match paper

### ISSUE THREAD

**Issue by hal-ler** [HexHive/HexVASAN#1]
This is the second time I had to report it. The first report led to an errata claiming that the code was changed to the correct implementation. This one is better, but it still does not match the paper. Was this ever implemented correctly?

**Comment by gannimo** [comment]
Thanks for the comment Istvan. Can you be more precise?

**Comment by hal-ler** [comment]
Look at the pseudo-code in the paper and how it handles recursion. The pseudo-code is the right way to do things. This code is not. Also you still simplify pointer types to a single id.

**Comment by gannimo** [comment]
Thanks. Feel free to send in a patch.
